## numpy

- документация: http://www.numpy.org/

In [1]:
import math

Библиотека numpy является удобным инструментом для работы с многомерными массивами с возможностью векторизации вычислений. Рассмотрим базовые вещи, которые можно делать с помощью нее.

In [2]:
import numpy as np

In [5]:
type([[1, 2], [3, 4], [5, 6]])

list

In [7]:
lst = [[1, 2], [3, 4], [5, 6]]

In [8]:
lst

[[1, 2], [3, 4], [5, 6]]

In [140]:
vec = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
type(vec)

numpy.ndarray

In [6]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
lst * 2

[[1, 2], [3, 4], [5, 6], [1, 2], [3, 4], [5, 6]]

In [12]:
new_vec = vec * 2

In [13]:
new_vec

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [11]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
vec @ vec

ValueError: ignored

In [141]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [142]:
product = vec @ vec.T

In [21]:
product

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [24]:
product[::-2][::-1]

array([[ 5, 11, 17],
       [17, 39, 61]])

In [19]:
vec[::-2]

array([[5, 6],
       [1, 2]])

In [26]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
vec[1][1]

4

In [45]:
vec1 = np.array([[1, 2], [3, 4], [5.0, 6]])

С чем мы работаем?

In [28]:
2 ** 64

18446744073709551616

In [44]:
vec1.dtype

dtype('<U32')

In [27]:
vec.dtype

dtype('int32')

In [ ]:
type(vec)

numpy.ndarray

Размер массива:

In [ ]:
dir(vec)

In [48]:
print(vec)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
vec.shape

(3, 2)

In [49]:
vec.T.shape

(2, 3)

Число осей:

In [51]:
vec2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [52]:
print(vec2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [53]:
vec.ndim

2

У некоторых функций бывает параметр `axis`, который позволяет применить эту функцию по разным осям - в данном случае, по строкам или столбцам:

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.sum(vec)

21

In [58]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [ ]:
np.sum(vec, axis=1)

array([ 3,  7, 11])

In [ ]:
vec.sum()

21

Транспонируем массив:

In [59]:
vec.T

array([[1, 3, 5],
       [2, 4, 6]])

In [60]:
vec.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

Обратите внимание, что переменная `vec` не поменялась!

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Размеры массивов можно менять:

In [69]:
temp = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(temp.shape)
temp1 = temp.reshape(3, 2, -1)
temp1

(12,)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [70]:
temp1.ndim

3

In [71]:
temp1.shape

(3, 2, 2)

In [76]:
vec.shape

(3, 2)

In [77]:
vec.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
vec.reshape(-1, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
vec.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [75]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

Индексирование:

In [80]:
vec[1:10:2, ::-1]

array([[4, 3]])

In [81]:
vec[1, 0]

3

In [82]:
vec[1][0]

3

In [86]:
vec[::-1, ::-2]

array([[6],
       [4],
       [2]])

In [ ]:
vec[1:2, 0]

array([3])

In [ ]:
vec[::2, :]

array([[1, 2],
       [5, 6]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
vec[::-2, 1]

array([6, 2])

Булевы массивы:

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
is_even = (vec % 2 == 0)
print(is_even)
type(is_even)

[[False  True]
 [False  True]
 [False  True]]


numpy.ndarray

In [88]:
np.sum(is_even)

3

Булевы массивы позволяют вытаскивать элементы с True из массива того же размера

In [89]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
is_even

array([[False,  True],
       [False,  True],
       [False,  True]])

In [90]:
vec[is_even == True]

array([2, 4, 6])

Иногда бывает полезно создавать специфичные массивы. Массив из нулей:

In [92]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Массив из единиц:

In [93]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Единичная матрица:

In [94]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Массивы можно объединять:

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
np.hstack((vec, np.zeros((3, 5))))

array([[1., 2., 0., 0., 0., 0., 0.],
       [3., 4., 0., 0., 0., 0., 0.],
       [5., 6., 0., 0., 0., 0., 0.]])

In [98]:
np.vstack((vec, np.zeros((7, 2))))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

И, наконец - арифметические операции!

In [99]:
vec + 1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [100]:
vec * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [101]:
vec ** 2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [ ]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
vec + vec ** 2

array([[ 2,  6],
       [12, 20],
       [30, 42]])

In [103]:
vec ** 3

array([[  1,   8],
       [ 27,  64],
       [125, 216]], dtype=int32)

In [104]:
vec * np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [105]:
vec * vec ** 2

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

In [106]:
np.sin(vec)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

Матричное умножение:

In [107]:
vec.dot(vec)

ValueError: ignored

In [108]:
vec.dot(vec.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [109]:
vec.dot((vec ** 2).T)

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

In [110]:
vec @ (vec ** 2).T

array([[  9,  41,  97],
       [ 19,  91, 219],
       [ 29, 141, 341]])

Broadcasting:
https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html

In [111]:
np.ones((2,))

array([1., 1.])

In [115]:
vec_t = np.array([[2, 2], [2, 2]])

In [114]:
np.zeros((2, 2)) * np.ones((2,))

array([[0., 0.],
       [0., 0.]])

In [117]:
vec_t * np.ones((2,))

array([[2., 2.],
       [2., 2.]])

In [123]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [122]:
np.arange(3).reshape(3, 1)

array([[0],
       [1],
       [2]])

In [124]:
vec + np.arange(3).reshape(3, 1)

array([[1, 2],
       [4, 5],
       [7, 8]])

Генерация случайных чисел:

In [ ]:
np.random.rand(2, 3)

array([[0.00422451, 0.39796618, 0.17185922],
       [0.96079367, 0.529853  , 0.30382593]])

In [ ]:
np.random.seed(2018)
np.random.rand(2, 3)

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539]])

In [ ]:
np.random.seed(2018)
np.random.rand(2, 3)

array([[0.88234931, 0.10432774, 0.90700933],
       [0.3063989 , 0.44640887, 0.58998539]])

In [ ]:
np.random.randn(3, 2)

array([[ 0.57376143,  0.28772767],
       [-0.23563426,  0.95349024],
       [-1.6896253 , -0.34494271]])

In [ ]:
np.random.normal(2, 1, size=3)

array([2.50227689, 2.8560293 , 1.85720992])

In [ ]:
np.random.randint(5, 10, size=3)

array([6, 5, 7])

Почему вообще используют `numpy`?

In [126]:
n = 300
A = np.random.rand(n, n)
B = np.random.rand(n, n)

In [128]:
A.shape

(300, 300)

In [129]:
%%time
C = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i, j] += A[i, k] * B[k, j]

Wall time: 13.7 s


In [130]:
%%time
C = A @ B

Wall time: 23 ms


### Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).
2. Найти максимальный нечетный элемент в массиве.
3. Замените все нечетные элементы массива на ваше любимое число.
4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если `n=5`, то ответом будет `array([9, 7, 5, 3, 1])`. *Функции, которые могут пригодиться при решении: `.arange()`*
5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. _Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`_
6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$. _Функции, которые могут пригодиться при решении: `.append()`_
7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [203]:
vec2 = np.identity(10)

In [204]:
vec2

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [205]:
np.array(list(set(vec2.reshape(1, -1)[0])))

array([0., 1.])

5.

In [179]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [180]:
a = 1.56

In [181]:
diff = np.abs(vec - a)

In [182]:
diff

array([[0.56, 0.44],
       [1.44, 2.44],
       [3.44, 4.44]])

In [193]:
np.min(diff)

0.43999999999999995

In [194]:
np.max(diff)

4.4399999999999995

In [186]:
vec.reshape(1, -1)[0][np.argmin(np.abs(vec - a))]

2

In [187]:
vec.reshape(1, -1)[0][np.argmax(np.abs(vec - a))]

6

2.

In [145]:
vec

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
max(vec[vec % 2 != 0])

5

1.

In [135]:
vec1 = np.array([1, 2, 3, 4, 5, 6, 7])

In [136]:
vec1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [143]:
product

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [144]:
product[::-1, ::-1]

array([[61, 39, 17],
       [39, 25, 11],
       [17, 11,  5]])

In [139]:
np.array(list(reversed(vec1)))

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
# ┌(▼▼メ)┘ └(メ▼▼)┐